name: 'PR Commenter'
description: 'Adds a comment to a PR that can differ depending on which files are being changed in that PR.'
author: angelikatyborska
inputs:
  github-token:
    description: 'Auth token used to manage issues or pull requests'
    default: ${{ github.token }}
    required: false
  config-file:
    description: 'The path to the configuration file'
    default: '.github/pr-commenter.yml'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'message-circle'
  color: 'purple'
