name: Test
on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 12.x

      - name: Install project dependencies
        run: npm install --also=dev

      - name: Run tests
        run: npm run test

      - name: Run linter
        run: npm run lint
